language: java
jdk:
  - openjdk8
services:
  - docker

# env:
#   global:
#     secure: DOCKER_USERNAME
#     secure: DOCKER_PASSWORD

# How to generate the travis encrypted value :
# brew install travis
# travis login --auto
# travis encrypt DOCKER_USERNAME=interviewdot
# travis encrypt DOCKER_PASSWORD=____________

# replace the following env configurations with your own
env:
  global:
    - secure: nEGaQcN5mBcNSdq1hp9H+AItSa8N5bJ4UPPSldJ4dlnieyowzjtth2menJ6IjvZkb8mSDiwINZ4LEdbc65Yn4A5fFGwT997U6WCljM/cIvS08GaOUsvke0gh3VxjHnU7yy8gBFsX2qICBTdWMWrnekaYz5TeJfLDRMa0zFFYqszN5vm7Gj51gsOmi+tOfgz+tc4z3PqNobBAGdyXlTAW5TAEEMW0UWMi+Qtsulrqzibi2glmSi/S3wXob94JXoZ8p8/YY3iSOwYqFP1GCtNkJvnJ7dASWaHcRVOfnk9anq1CT83FSDTQnr23+7/D4NssHsMoy3LdRf+N3hc/lpHKUrHvB+PnpPm/psku4KMbB7riTa52+JwWXwsTdD+2/GjQGCVxba+wlJ0D1biwvyXWszPQzptosFK06oOtJ8UgCXafqKRFF1ylWGiTflvj5X9uqjO6TJo7wgiDeNOD/j/ZsGMvCsKVdY1rdFXHfH9X0itQZTd2AqSb9QDq927Z+IJuysdc0ZXJjLbvirPPO+RWwfA5n1liWNklimzuXvj5UBnZuNPG7oBOEqVaDy3ToaXxiZfOuWL6Y3UZ5R9mF4dbO8J/tRf5brhmMGQ1MfdR3zK/rgKP1Y31RNgWLinnF4CTXttUPzKGmMysahTJCWH89ZLlg9FRVZsJVD0eryTwMl4=
    - secure: VYfhN/uCa2+J8liRqIyF4l9J7rZWHs14zgmboYniMxwCrGlnlztVV2MKDSMRru/XB9ykCpeIWLjTdcgWHyyjGpC/pJKZKEA3nKoVSwbcvDxGmKkCRLFM1NNxt8JOjzgZ7JApMrYvCdhEUab+0bTlK1Wd0pVvyVs+eSAK+m5/LkgW0WAZ6r9mLNjtuMcP883ubMFJFdtsBhZAw7qNyQ/sRrI80qHE91N0a+XXOWnZq2VEYxtvakU3G9YNOnGctwL44dvdsUTfCCzvTG3lVGaLbp8XxDFfGgGywq9iI5wjruCb3uTV/tu1Sc+OQbX2/5PeOletmKD5ps9Ct51rD5bdiRvwj/SXgiC/eUbcP6QDOK0xq3Us90jhb57oRHnxitiGoh+PdrA2ti3xQWVuat6BwxWHQuMG6zxg0rb4ufCMI962wEl4q2LjCLaqBQrU3XRtDC9GAHcflx08CeT66lj1MJBtZIM+4zJk+IZtrzo28VEIACrcRDmIgjhRKReLAWnpghOby6Y4dITP1+ZU7MvWet+faOUON1FW+YWG2lP0i45ky3oqdPgofhcRMtgUYlmpvMu0AG//ZshFrDNzTp880s47c0uCqhb1fXmzt6elZXA1I4S/dVtrCd7MRZmtxGW/Qcq6WFi4QJLEVO0aqQQq00tEifGnZyOJlUlvepBWL00=

before_install:
  - docker pull openjdk:8-jdk-alpine

# Test & Build SpringBoot app
script:
  - mvn test
  - mvn clean package
  # Create Docker image for our app and push it to Dockerhub repository
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t travis-demo .
  - docker images
  - docker tag travis-demo interviewdot/travis-demo
  - docker push interviewdot/travis-demo

# Send the message of success after the docker image is pushed to dockerhub
notifications:
  email:
    - mounik.rdg@gmail.com


